// src/AppStyles.ts
import type { CSSProperties } from 'react';

export const styles: { [key: string]: CSSProperties } = {
    page: {
        minHeight: '100vh',
        width: '100vw',
        background: 'linear-gradient(135deg, #18181b 0%, #312e81 100%)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    card: {
        background: '#232136',
        borderRadius: 16,
        boxShadow: '0 4px 24px rgba(0,0,0,0.18)',
        padding: 36,
        maxWidth: 420,
        width: '100%',
    },
    header: {
        display: 'flex',
        alignItems: 'center',
        marginBottom: 24,
    },
    logo: {
        width: 40,
        height: 40,
        marginRight: 12,
    },
    title: {
        margin: 0,
        fontWeight: 700,
        fontSize: 24,
        color: '#a5b4fc',
        letterSpacing: 0.5,
    },
    form: {
        display: 'flex',
        flexDirection: 'column',
        gap: 18,
    },
    label: {
        fontWeight: 500,
        color: '#818cf8',
    },
    labelBlock: {
        fontWeight: 500,
        color: '#818cf8',
        display: 'block',
        marginBottom: 6,
    },
    input: {
        marginTop: 6,
        width: '100%',
        background: '#18181b',
        color: '#f4f4f5',
        border: '1px solid #3730a3',
        borderRadius: 6,
        padding: 6,
    },
    select: {
        width: '100%',
        borderRadius: 6,
        border: '1px solid #3730a3',
        padding: 10,
        background: '#18181b',
        color: '#f4f4f5',
        fontSize: 16,
    },
    button: {
        marginTop: 10,
        background: 'linear-gradient(90deg, #6366f1 0%, #818cf8 100%)',
        color: 'white',
        border: 'none',
        borderRadius: 8,
        padding: '10px 0',
        fontWeight: 600,
        fontSize: 16,
        cursor: 'pointer',
        boxShadow: '0 2px 8px rgba(99,102,241,0.18)',
    },
    buttonDisabled: {
        cursor: 'not-allowed',
        opacity: 0.7,
    },
    result: {
        marginTop: 28,
        fontWeight: 'bold',
        fontSize: 20,
        color: '#4ade80',
        textAlign: 'center',
        background: '#1e293b',
        borderRadius: 8,
        padding: 16,
        border: '1px solid #4ade80',
    },
    resultValue: {
        color: '#22d3ee',
    },
    error: {
        color: '#f87171',
        marginTop: 16,
        textAlign: 'center',
        background: '#1e293b',
        borderRadius: 8,
        padding: 12,
        border: '1px solid #f87171',
    },
};
